### ISSUE TITLE
Sorting clubs yields weird results

### ISSUE THREAD

**Issue by toniperic** [Blackmorse/hat-all-stats#172]
Hi, thanks for the great work!

I have tried sorting clubs in specific series from least conceding teams to most conceding, but [have gotten some weird results](https://hattid.com/divisionlevel/formalTeamStats?leagueId=58&divisionLevel=4&season=75&page=0&statType=statRound&statRoundNumber=13&sortBy=missed&pageSize=16&sortDirection=asc) – the top team is a team that played one game without conceding. 

I guess that is technically correct (since they conceded none), but that should not be the default behaviour as the team has lost owner and/or does not exist anymore.

**Comment by Blackmorse** [comment]
@toniperic , thanks for rising an issue.

Right, seems that "technical" behaviour is correct, but of course It's better to have more correct information.

Problem is that I can't track all teams. Because of that I'm tracking only active teams. WHen team loses owner , It will not be tracked anymore. The same if team have changed  the owner - for me now it is a new team.

Do you have any ideas?
My first idea is to add checkbox like 'show only teams who played the full season'

**Comment by toniperic** [comment]
That sounds good to me.

Can you maybe make that default behaviour, with an optional checkbox for including teams that have not played the full season?

**Comment by Blackmorse** [comment]
@toniperic , Ok, seems it's better decision
For me this issue doens't look like critical
I will think how to resolve it as much as possible, but probably to avoid duplication of efforts I may defer it until migration to new front-end

**Comment by Blackmorse** [comment]
@toniperic I've added the checkbox. You can check that :)
